server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/goodme?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: huangziweijinx
  redis:
    host: localhost
    port: 6379
    database: 0

logging:
  level:
    com.goodme: debug 