server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://mysql:3306/goodme?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD:huangziweijinx}
  redis:
    host: ${REDIS_HOST:redis}
    port: ${REDIS_PORT:6379}
    database: 0
    password: ${REDIS_PASSWORD:}

logging:
  level:
    com.goodme: info
    org.springframework: warn
  file:
    name: /var/logs/goodme-backend.log

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.nologging.NoLoggingImpl 